### ISSUE TITLE
500 Server error

### ISSUE THREAD

**Issue by EasyByNets** [DIBS-Payment-Services/Prestashop1_dibseasy#1]
I tried to make some payments and I managed to receive an 500 server error. The log said: 

*ERROR* 	2017/07/25 - 06:19:26: Property Customer->lastname is not valid at line 909 in file classes/ObjectModel.php

Could we define these kinds of errors instead of dying with an 500 error? :)

**Comment by rokaszygmantas** [comment]
Hello,

I've implemented the validation of new customer's account before saving it on prestashop so now it will display error messages if the account cannot be created. Fixed in both module versions.

Regards,
Rokas
