### ISSUE TITLE
Live payments fail

### ISSUE THREAD

**Issue by EasyByNets** [DIBS-Payment-Services/Prestashop1_dibseasy#3]
Tried making live payments with both our own test-shop, and your demo shop. Can you help investigate?

This is what I got as response from Nets:

-        The URL used to integrate the Checkout, as example https://ukrmodules.dibs.dk/page?param1=a&xxx...)
-        The js params used to start the checkout, as example
 
var checkoutOptions = {
checkoutKey: "[guid]",                   //[Required] GUID without dashes
partnerMerchantNumber: "",   //[optional] Number
 
paymentId : "[GUID]",         //[required] GUID without dashes
containerId : "dibs-complete-checkout", //[optional] defaultValue: dibs-checkout-content
language: "",            //[optional] defaultValue: en-GB
};
 
var checkout = new Dibs.Checkout(checkoutOptions);
 
It looks like the integrator is using a special URL parameter called “&skipdfp=” (usually used in the 3DS flow), but without the correct scenario/context, because a previous connected consumer to the payment is needed.

**Comment by EasyByNets** [comment]
I also tested your demo with same error and this is the url: http://grazus.lt/demo/clients/dibs/ps15/en/module/dibs/checkout?paymentId=e8c35c8eed8f48e78c5997362a19d3d3

**Comment by rokaszygmantas** [comment]
Could you please give us the steps to recreate this issue on our demo site? Thanks!

**Comment by EasyByNets** [comment]
1) go to this page and add product to the basket: http://grazus.lt/demo/clients/dibs/ps15/en/music-ipods/1-ipod-nano.html
2) go to checkout 
3) Click "International customer?"
4) create a fake user, and select Sweden as country. Click "continue"
5) Enter a real visa/master card (wont be charged, dont worry)
6) click pay and you will now be redirected back with an error

**Comment by rokaszygmantas** [comment]
Thank you for the information. We will investigate this.

**Comment by EasyByNets** [comment]
@rokaszygmantas I just got this answer that should show how to fix the issue:

Hi, we have found the issue in your integration.
You are not allowed to use a query string containing PaymentId=xxx, it is mentioned as a part of a 3D secure flow:
 
[…]
3D-Secure Checkout Flow
If a customer has a 3Dsecure enrolled card, they will be redirected to verification during the checkout-process. When the customer has completed the verification, they are automatically returned back to the checkoutUrl with an added paymentId parameter.
[...]
 
The tech site (http://tech.dibspayment.com/easy/integration-guide) will be update asap to be more explicit about this.
 
So to fix this issue, “paymentId=xxx” should be renamed - as example - to “pid=xxx” (or which name you like).
This will not work
http://grazus.lt/demo/clients/dibs/ps15/en/module/dibs/checkout?paymentId=e8c35c8eed8f48e78c5997362a19d3d3
 
This will work
http://grazus.lt/demo/clients/dibs/ps15/en/module/dibs/checkout?pid=e8c35c8eed8f48e78c5997362a19d3d3

**Comment by sarjon** [comment]
As I understand we should take payment ID which is added to the checkout url after verification and reinitialize checkout process, is it correct? If so, how this parameter is called? Is it just "pid"?

**Comment by EasyByNets** [comment]
I have been told by a supporter, that your assumption it correct :)

**Comment by sarjon** [comment]
Is it possible to test this functionality while module is in testing mode? Cus at the moment it wont redirect to verification site.

**Comment by EasyByNets** [comment]
It should work on the test-mode as well.

**Comment by sarjon** [comment]
Actually I cannot reproduce the issue, I think there's no 3Dsecure enrolled card in testing cards.

**Comment by EasyByNets** [comment]
I did not register that it was due to 3D secure, in that case no we cannot test on the test mode.
I can use my own Visa card for test if you could push a potential fix on  http://grazus.lt/demo/clients/dibs/ps15 ?

**Comment by sarjon** [comment]
Could you provide us with 3D secure card so we can reproduce the issue and fix it?

**Comment by EasyByNets** [comment]
I'm still waiting for an answer on this, but so far that is not possible, I'm just using my own Visa card for test.

**Comment by EasyByNets** [comment]
You are not able to release a fix and let me test it with my own card?

**Comment by sarjon** [comment]
Well, we can release a fix and assume that payment ID name that is added to checkout url is called "pid" and use it to reinitialize checkout.

**Comment by sarjon** [comment]
I have updated module according to your comments. Payment ID is now taken from "pid" parameter to reinitialize checkout when customer is redirected back to checkout url.

**Comment by EasyByNets** [comment]
I just tested: http://grazus.lt/demo/clients/dibs/ps15/en/module/dibs/checkout?paymentId=da9dae12993a4741a9c40fdc96f303b4

It looks like the same error, but will try and ask the team if they can see the error

**Comment by sarjon** [comment]
Where does http://grazus.lt/demo/clients/dibs/ps15/en/module/dibs/checkout?paymentId=da9dae12993a4741a9c40fdc96f303b4 link come from? Is this the link where you are redirected?

**Comment by EasyByNets** [comment]
Yes 👍

**Comment by sarjon** [comment]
ok, it seems that DIBS system adds paymentId as query parameter. Will this parameter name change or should we adapt the module to this behaviour?

**Comment by EasyByNets** [comment]
I have just been told that should adapt the module to the behaviour.

**Comment by sarjon** [comment]
Module has been updated, you can test it in 1.5 & 1.6 demo sites. If this fix solves the issue, i'll update 1.7 version as well.

**Comment by EasyByNets** [comment]
I now get this message: 

![screen shot 2017-07-31 at 15 33 37](https://user-images.githubusercontent.com/23499563/28780049-b4f66648-7605-11e7-8f5e-12e99c826659.png)

**Comment by sarjon** [comment]
This issue is fixed and demo sites are updated.

**Comment by EasyByNets** [comment]
Great job, Šarūnas.

It looks like this is fixed, I got the payment confirmed and recieved email as well.
Will close this ticket.
