### ISSUE TITLE
Wont install on prestashop 1.6.1.11

### ISSUE THREAD

**Issue by adressopost** [DIBS-Payment-Services/Prestashop1_dibseasy#4]
Tried to upload the module but can´t find it on module list to install after we uploaded it
We also tried to manually install via ftp, with same result . changed folder access rights temporary to 777 same results.
we can install and upload all other module on market

We use Prestashop 1.6.1.11
Tried clear cache
cashing is off
Tried force compilation 

Best regard Mattias

**Comment by sarjon** [comment]
hi @adressopost download module as ZIP file and make sure zip filename is "dibs" and folder inside it is also named as "dibs".

**Comment by adressopost** [comment]
Hi works like a charm
Thanks!

**Comment by adressopost** [comment]
Hi we can somebody help us? or is this the wrong place ta ask?

we use a non standard theme and onepage checkout module and we cant get the module to work.

when we place the order button the shop just send us to : http://www.azzo.se/module/dibs/checkout
and same with the button " Go to checkout"

HTTP ERROR 500

Mattias@adressoposts.e

**Comment by sarjon** [comment]
hi @adressopost, can you provide more details related to the error?

**Comment by adressopost** [comment]
Hello, we finally resolved the problem. We had an older version of PHP, so after an update to PHP-version 5.6.21, everything works well now.
Best regard
