### ISSUE TITLE
Same user payment declined

### ISSUE THREAD

**Issue by EasyByNets** [DIBS-Payment-Services/Prestashop1_dibseasy#5]
As you can see on this screenshot, I'm not able to pay after I already have payed with the same email once. This error message comes after I have clicked on the pay button and was redirected back from 3DS:
![screen shot 2017-09-14 at 08 51 33](https://user-images.githubusercontent.com/23499563/30415835-223562ee-992a-11e7-8e60-689945c53fd9.png)

**Comment by sarjon** [comment]
hi @EasyByNets, you must sign in if customer already exists in order to pay. If it's a new customer, then you would be registered automatically and signed in.

**Comment by EasyByNets** [comment]
Is that a setting that can be changed in the PS admin? 
I dont understand why you would need to login just because you already have a user? This will just add an extra step to the payment flow.

**Comment by sarjon** [comment]
You must be logged in to access order confirmation page.

**Comment by EasyByNets** [comment]
Ok, this makes sense.

Thanks for your help. Have a great day.
